name: Publish

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'version bump'
        required: true
        type: choice
        default: 'patch'
        options:
          - major
          - minor
          - patch
      version:
        type: string
        description: 'Alternative: set explicit version'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: npm
          token: ${{ secrets.NPM_TOKEN }}
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npx lerna publish ${{ inputs.version || inputs.bump }} -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}