name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm ci
      # - run: npm test
      - run: npm version ${TAG_NAME} --git-tag-version=false -ws
        env:
          TAG_NAME: ${{ github.event.release.tag_name || inputs.tag }}
      - run: npm --ignore-scripts publish --access public -ws
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}