name: Publish

on:
  release:
    types: [created, edited]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm ci
      # - run: npx lerna version --no-push --no-git-tag-version -y ${TAG_NAME}
      #   env:
      #     TAG_NAME: ${{ github.event.release.tag_name || inputs.tag }}
      - run: npx lerna publish from-git
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}