name: Publish

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'version bump'
        required: true
        type: choice
        default: 'patch'
        options:
          - major
          - minor
          - patch
      tag:
        type: string
        description: 'tag name'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: npm
          token: ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - run: npx lerna publish ${{ inputs.bump }} -y --loglevel silly --no-verify-access
      - run: npx lerna publish ${{ inputs.tag }} -y --loglevel silly --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}